### ISSUE TITLE
Roadmap features

### ISSUE THREAD

**Issue by jasondevj** [jagornet/dhcp#18]
Do you have a roadmap feature list that your planning to implement?

**Comment by jasondevj** [comment]
also do you have any plans to support hot reload of configuration without needing a restart?

**Comment by agrabil** [comment]
Yes, the next major release is 3.0 and includes the following features:
- DHCP Failover
- Performance enhancements
- Additional options support
- Full support for Java 8
- Updates to third party libs

**Comment by agrabil** [comment]
Hot reload has been a target feature from the beginning, but has not been as high on the priority list as others listed above.

**Comment by jasondevj** [comment]
Thanks agrabil for the info, is there a plan date for 3.0? also can I help out with the hot reload? I'm looking at implementing the feature, if it's something you guys are looking at I can send a pull request when I'm done.

**Comment by agrabil** [comment]
The project plans are not yet complete, but we are targeting Q1 2017 for Jagornet DHCP 3.0.  We will review any pull requests and incorporate changes that fit with the architecture and product vision.

**Comment by selangley** [comment]
Hello. 
I'm curious if development on this project is continuing.
Thanks!

**Comment by agrabil** [comment]
Yes, Jagornet DHCP 3.0 is in development.  Dev branch converted to Maven build with three submodules - core, client, server.  Working on failover and several other updates.  Thanks for your interest in this project.
