### ISSUE TITLE
How to update DHCPv4 Address Bindings without restart

### ISSUE THREAD

**Issue by iigx** [jagornet/dhcp#23]
I'd like to update static DHCPv4 address bindings dynamically.
However, there is not update command and rest api.
Is it possible?

**Comment by agrabil** [comment]
Sorry, this is not yet possible.

**Comment by agrabil** [comment]
Leaving this issue open.  Enhanced REST API for configuration and management is planned for Jagornet 4.0.

**Comment by agrabil** [comment]
This can be accomplished by updating the server configuration via the REST API in the 4.0.0 release.
