### ISSUE TITLE
Incorrectly checks for port availability on all NIs for IPv4 broadcast

### ISSUE THREAD

**Issue by trreeves** [jagornet/dhcp#48]
I have many network interfaces on a server machine, and I want to be able to configure Jagornet to act as a DHCP server for a network that is attached to just one of those interfaces. I have configured Jagornet with the `--v4bcast` parameter to listen on just one network interface. There is already another process using port 67 for another network interface on the server.

The following code shows that Jagornet actually checks that the broadcast port is available on all network interfaces on the host machine, when should it actually just need to check that the port is available on the network interfaces configured for broadcast?

https://github.com/jagornet/dhcp/blob/f2d58450044e8cad572d53d7e0ba0de2dd059706/Jagornet-DHCP/dhcp-server/src/main/java/com/jagornet/dhcp/server/netty/NettyDhcpServer.java#L224

It looks like this could be a simple code change to use a different constructor for DatagramSocket that accepts the IP address as well as the port...
https://docs.oracle.com/javase/7/docs/api/java/net/DatagramSocket.html

**Comment by trreeves** [comment]
It could also be nice to add some details in the logs when checking for port availability, to let the user know which IPs/Ports are not available. I was able to work it out by reading the code, but a little extra help would be nice.

**Comment by trreeves** [comment]
@agrabil Do you have any opinion on this issue?

**Comment by agrabil** [comment]
It seems quite risky to run multiple DHCP servers on the same machine, even if they are listening on different IPs.  However, I suppose there is no reason why you should not be able to, assuming you know what you are doing.

**Comment by trreeves** [comment]
@agrabil A little more info on my use case here... 

I'm trying to put together a nice approach for reliably using Hyper-VMs for development purposes on our corporate Windows machines.  There are IT policies and VPN clients that are beyond my control running on the machines, which are making life more difficult than they need to be. So I am going the route of having a NAT'd local network, connected to a Hyper-V internal switch, with a DHCP server running on that network (and only that network).  Then I can use Vagrant to provide a nice mechanism of provisioning multiple HyperV VMs on to that network.  

The HyperV Default Switch that you get out of the box actually provides a NAT'd network & DHCP server, but you cannot control the IP address space of its network (or configure its DHCP server to set IP address lease times or set static IPs), and so it doesn't play nicely with our VPN clients and VMs frequently fail to get network connectivity. 

So it is the HyperV Default Switch that is already running a DHCP server on the machine, bound to port 67 on it's network interface.  Meanwhile, I'm trying to run Jagornet to serve VMs running on my own local network on the machine.

So any Windows machine that has HyperV enabled would probably encounter this issue.

**Comment by agrabil** [comment]
Thanks for the detailed explanation of your use case.  It helps to understand how folks are using Jagornet.  The fix for this issue has been committed to the develop branch.  It will be included in the next release build.

**Comment by trreeves** [comment]
Great. Many thanks to you for putting the time and effort into these
changes.
