### ISSUE TITLE
Likely incorrect loop increments in `BaseOpaqueDataListOption`

### ISSUE THREAD

**Issue by jstuyts** [jagornet/dhcp#8]
There are two loops in `BaseOpaqueDataListOption` that use `j` as the loop variable, but both of theses loops increment `i`. See lines 196 and 246.

**Comment by agrabil** [comment]
Thanks for finding this!
Greg

Date: Sun, 24 Jan 2016 01:29:32 -0800

**Comment by agrabil** [comment]
Resolved by commit 62470b8d0527e003b0b1ada025c183e0f0ac5432
