### ISSUE TITLE
Missing braces in `findBindingPool(InetAddress)` results in first pool always being returned

### ISSUE THREAD

**Issue by jstuyts** [jagornet/dhcp#9]
Although the indentation in `findBindingPool(InetAddress)` of `BaseBindingManager` suggests otherwise, the `return` statement is not part of the `if` block. This results in the first binding pool of the first list of binding pools to be always returned.

Adding braces to the `if` statement around the logging and `return` statements will resolve this.

**Comment by agrabil** [comment]
And thank you for this one too!
Greg

Date: Sun, 24 Jan 2016 02:45:12 -0800

**Comment by agrabil** [comment]
Resolved by commit cb26a845a126d54cdd809ea178a8ec7831c6e530
